1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np
b = np.zeros((100))
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2.Создать вектор размера 100, заполненный единицами

In [4]:
b = np.ones((100))
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3.Создать вектор размера 100, заполненный числом 3

In [5]:
B = np.ones((100))
B*3

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [8]:
b = np.full(100, 3)
b

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

4. Как получить документацию о функции numpy.add из командной строки?

In [10]:
python3 -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-10-e4a7e6a4f2e9>, line 1)

In [11]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

5. Поменять 2 строки в матрице

In [14]:
a = np.arange(4).reshape((2,2))
a[[0,1]] = a[[1,0]]
a

array([[2, 3],
       [0, 1]])

6. Создать вектор со значениями от 10 до 100

In [15]:
a = np.arange(10, 100)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

7. Развернуть вектор (первый становится последним)

In [17]:
a = np.arange(4)
a = a[::-1]
a

array([3, 2, 1, 0])


8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [18]:
a = np.arange(16).reshape((4, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [20]:
a = np.array([1, 2, 3, 4, 5])
i = 3
b = np.zeros(len(a) + (len(a) - 1)*(i))
b[::i+1] = a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

10. Создать 3x3 единичную матрицу

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

11. Создать массив 3x3x3 со случайными значениями

In [22]:
a = np.random.rand(3, 3, 3)
a

array([[[0.51507212, 0.66804411, 0.37257829],
        [0.50409408, 0.03467406, 0.21575733],
        [0.19145253, 0.23612447, 0.9610979 ]],

       [[0.6610478 , 0.92845257, 0.14789874],
        [0.59765973, 0.79343442, 0.95411877],
        [0.33450365, 0.10065205, 0.23425456]],

       [[0.24779885, 0.11951746, 0.31720158],
        [0.84134635, 0.14251349, 0.06854473],
        [0.84440172, 0.75279603, 0.94302032]]])

12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [24]:
a = np.random.rand(10, 10)
min = a.min()
max = a.max()
a, min, max

(array([[0.93053757, 0.00988042, 0.18667741, 0.32511621, 0.50938781,
         0.2343961 , 0.0133279 , 0.11231702, 0.59562903, 0.97403306],
        [0.22084687, 0.2491374 , 0.3876743 , 0.34377261, 0.27929779,
         0.56334291, 0.0053413 , 0.25787406, 0.98741484, 0.77941504],
        [0.25607787, 0.94288229, 0.53776467, 0.09932243, 0.99286153,
         0.37771862, 0.83874453, 0.69541811, 0.3016983 , 0.45831366],
        [0.35743219, 0.18061953, 0.40157173, 0.92946657, 0.6178709 ,
         0.34857559, 0.86728303, 0.27821148, 0.38167299, 0.82773464],
        [0.9549186 , 0.60965326, 0.72426969, 0.80571021, 0.51104583,
         0.02937817, 0.9753129 , 0.66621496, 0.51764786, 0.64830953],
        [0.4379269 , 0.35387691, 0.0880262 , 0.72446234, 0.99845548,
         0.37614979, 0.2809773 , 0.34080922, 0.08203163, 0.29672373],
        [0.43635351, 0.96218504, 0.30554946, 0.88369386, 0.65233569,
         0.06753347, 0.76335859, 0.75001393, 0.98116955, 0.72335463],
        [0.57946554, 0.8384

13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [26]:
a = np.random.rand(30)
srznach = a.mean()
srznach

0.5931031953630295

14. Создать матрицу с 0 внутри, и 1 на границах

In [29]:
a = np.ones((6, 6))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [3]:

a = np.random.random([10, 3])
x = a[:,0]
y = a[:,1]
b = np.hypot(x,y)
c = np.arctan2(y, x)
b, c

(array([0.66475097, 0.82032998, 0.15913656, 1.20531735, 0.84386811,
        1.12638813, 1.15239195, 0.4186765 , 1.16949808, 0.40924525]),
 array([1.24165449, 1.31016885, 0.01355962, 0.67648786, 1.28695952,
        0.68243548, 0.87615801, 1.39622557, 0.93547759, 0.76139384]))

16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [35]:
a = np.diag(np.array([1, 2, 2, 4]), k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [36]:
a = np.ones((8,8), dtype = int)
a[1::2, ::2] = 0
a[::2, 1::2] = 0
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [37]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [38]:
a = [0, 1]
b = np.tile(a , (8, 4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

20. Перемножить матрицы 5x3 и 3x2

In [43]:
a = np.arange(15).reshape((5, 3))
b = np.arange(6).reshape((3, 2))
c = np.dot(a, b)
a, b, c

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]), array([[0, 1],
        [2, 3],
        [4, 5]]), array([[ 10,  13],
        [ 28,  40],
        [ 46,  67],
        [ 64,  94],
        [ 82, 121]]))

21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [46]:
a = np.arange(15)
a[(a>3) & (a <= 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

23. Создать 5x5 матрицу со значениями в строках от 0 до 4¶

In [48]:
a = np.arange(5)
np.tile(a, (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

24. Есть генератор, сделать с его помощью массив

In [51]:
def generate(): 
    for x in range(10): 
        yield x 

a = np.fromiter(generate(), dtype='float', count=-1) 
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [54]:
a = np.linspace(0, 1 , 12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

26. Отсортировать вектор

In [56]:
a = np.array([4, 100, 34, 34, 23, 54])
a.sort()
a

array([  4,  23,  34,  34,  54, 100])

27. Проверить, одинаковы ли 2 numpy массива

In [57]:
a = np.array([4, 100, 34, 34, 23, 54])
b = np.array([4, 100, 34, 34, 23, 54])
np.allclose(a, b)

True

28. Сделать массив неизменяемым

In [60]:
a = np.array([4, 100, 34, 34, 23, 54])
a.flags.writeable = False

29. Найти n наибольших значений в массиве

In [63]:
a = np.arange(100)
n=15

a[np.argpartition(-a,n)[:n]]


array([88, 96, 92, 99, 98, 95, 94, 93, 97, 91, 90, 89, 87, 85, 86])

30. Заменить максимальный элемент на ноль

In [65]:
a = np.array([4, 100, 34, 34, 23, 54])
a[a.argmax()]=0
a

array([ 4,  0, 34, 34, 23, 54])

31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [66]:
a = np.zeros((10, 10), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1 , 10), np.linspace(0,1,10))
a

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [67]:
a = np.arange(8) 
b= a + 0.5 
C = 1.0 / np.subtract.outer(a,b)
np.linalg.det(C) 

3638.1636371179666

33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [72]:
for dtype in [np.int8, np.int32, np.int64]: 
    print(np.iinfo(dtype).min) 
    print(np.iinfo(dtype).max) 
for dtype in [np.float32, np.float64]: 
    print(np.finfo(dtype).min) 
    print(np.finfo(dtype).max) 
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


34. Напечатать все значения в массиве

In [2]:
import numpy as np
a = np.arange(15*25).reshape(15, 25)
np.set_printoptions(threshold = np.nan)
a

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

35. Найти ближайшее к заданному значению число в заданном массиве

In [4]:
a = np.arange(100)
b = np.random.uniform(0, 100)
num = (np.abs(a-b)).argmin()
a[num]


61

36. Преобразовать массив из float в int

In [6]:
a = np.arange(15, dtype=np.int32)
a = a.astype(np.float, copy=False)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

37. Каков эквивалент функции enumerate для numpy массивов?

In [10]:
a = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


38. Случайно расположить p элементов в 2D массив

In [12]:
n = 6
p = 7
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace = False), 1)
a


array([[0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

39. Отнять среднее из каждой строки в матрице

In [14]:
a = np.random.rand(5, 5)
b = a - a.mean(axis = 1, keepdims = True)
a

array([[0.89490684, 0.51515329, 0.42367641, 0.65366786, 0.89806558],
       [0.2977196 , 0.58329687, 0.09979057, 0.79283615, 0.56581862],
       [0.71950453, 0.16558412, 0.91907596, 0.48840313, 0.04639302],
       [0.75620615, 0.77693742, 0.11365822, 0.62981144, 0.59139957],
       [0.94399813, 0.56448791, 0.81825322, 0.32574372, 0.417088  ]])

40. Отсортировать матрицу по n-ому столбцу

In [4]:
import numpy as np
a = np.random.randint(0, 25, (5,5))
n = 4
print(a)
print(a[a[:,n].argsort()])



[[16  8  1  6  4]
 [15 15  7 16  9]
 [14 24  5 13  0]
 [ 2 23 19  0 16]
 [24  4  8 10 17]]
[[14 24  5 13  0]
 [16  8  1  6  4]
 [15 15  7 16  9]
 [ 2 23 19  0 16]
 [24  4  8 10 17]]


41. Определить, есть ли в 2D массиве нулевые столбцы

In [5]:
a = np.zeros((6,6))
(~a.any(axis=0).any())

True

42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [10]:
a = np.ones(8)
b = np.random.randint(0, len(a), 8)
a += np.bincount(b, minlength=len(a))
a, b

(array([1., 2., 1., 3., 3., 4., 1., 1.]), array([1, 5, 4, 3, 5, 4, 5, 3]))

43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [14]:
w,h = 16, 16
a = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
b = a[..., 0]*256*256+a[...,1]*256+a[...,2]
n=len(np.unique(b))
np.unique(n)

array([4])

44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [11]:
a = np.random.randint(0, 10 , (3, 4, 3, 4))
sum = a.reshape(a.shape[:-2]+(-1,)).sum(axis=-1)
sum

array([[58, 62, 58, 52],
       [45, 57, 64, 53],
       [66, 59, 43, 56]])